smartgenius/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('model/', views.model, name='model'),
    path('signup/', views.signup, name='Registro'),
    path('profile/', views.profile, name='perfil'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('inicio/', views.inicio, name='inicio'),
    path('cambiar_contrasena/', views.change_password, name='cambiar_contrasena'),
    path('get_user_data/', views.get_user_data, name='get_user_data'),
    path('edit_perfil/', views.edit_usuario, name='edit_perfil'),

    # Sección unidad
    path('unidad/', views.vwUnidad, name='unidad'),
    path('create_unidad/', views.create_unidad, name='create_unidad'),
    path('edit_unidad/', views.edit_unidad, name='editar_unidad'),
    path('obtener_unidad/', views.vwGetUnidad, name='obtener_unidad'),
    path('buscar_unidad/', views.vwBuscarUnidad, name='buscar_unidad'),
    path('eliminar_unidad/', views.vwEliminarUnidad, name='eliminar_unidad'),

    # Sección contenido
    path('contenido/', views.vwcontenido, name='contenido'),
    path('obtener_unidades/', views.vwObtener_Unidad, name='unidad_contenido'),
    path('create_contenido/', views.create_contenido, name='create_contenido'),
    path('unidad_seleccionada/', views.vwGetUnidad_Contenido, name='unidad_seleccionada'),
    path('edit_contenido/', views.vwEditar_Contenido, name='editar_contenido'),
    path('eliminar_contenido/', views.vwEliminarContenido, name='eliminar_contenido'),

    # Sección contenido
    path('temas/', views.vwTemas, name='temas'),
    path('obtener_contenido/', views.vwObtener_Contenido, name='contenido_tema'),
    path('create_tema/', views.vwCreate_tema, name='create_tema'),
    path('contenido_seleccionada/', views.vwGetContenido_Tema, name='contenido_seleccionada'),
    path('edit_tema/', views.vwEditar_Tema, name='editar_tema'),
    path('eliminar_tema/', views.vwEliminarTema, name='eliminar_tema'),

    # Sección material
    path('material/', views.vwMaterial, name='material'),
    path('material_seleccionada/', views.vwGetMaterial_Tema, name='material_seleccionada'),
    path('ejercicio_material/',views.vwGetMaterial_ejercicio, name='ejercicio_material'),
    path('obtener_temas/', views.vwObtener_Temas, name='obtener_temas'),
    path('create_material/', views.vwCreate_material, name='create_material'),
    path('eliminar_material/', views.vwEliminarMaterial, name='eliminar_material'),
    path('edit_material/', views.vwEdit_Material, name='edit_material'),

    # Sección ejercicio
    path('create_ejercicio/', views.vwCreate_ejercicio, name='create_ejercicio'),
    path('eliminar_ejercicio/', views.vwEliminarEjercicio, name='eliminar_ejercicio'),

     # Sección contenido - Alumno
    path('contenido_alumno/', views.vwContenidoAlumno, name='contenido_alu'),
    path('getcontenido_alumno/', views.get_material_by_tema_id,name='getcontenido_alumno'),
    path('avance_alumno/', views.visualizar_puntuacion, name='avance_alu'),
    path('obtener_contenidos/', views.obtener_contenidos, name='obtener_contenidos'),
    path('obtener_temas_contenido/', views.obtener_temas_contenido, name='obtener_temas_contenido'),
    path('obtener_ejercicios/', views.obtener_ejercicios, name='obtener_ejercicios'),
    path('obtener_materiales/', views.obtener_materiales, name='obtener_materiales'),
    path('visualizar_puntuacion_filtrada/', views.visualizar_puntuacion_filtrada, name='visualizar_puntuacion_filtrada'),
    path('visualizar_ejercicio_user/', views.obtener_ejercicios_visualizacion, name='visualizar_ejercicio_user'),

    #perfil
    path('cambiar_contrasena/', views.change_password, name='cambiar_contrasena'),
    path('get_user_data/', views.get_user_data, name='get_user_data'),
    path('edit_perfil/', views.edit_usuario, name='edit_perfil'),

    #Sección perfil - Alumno
    path('contenido_alumno/temas/', views.vwTemaAlumno, name='temas_alu'),
    path('perfil_alumno/', views.vwPerfilAlumno, name='perfil_alu'),
    path('obtener_puntuacion_por_tema/', views.obtener_puntuacion_por_tema, name='obtener_puntuacion_por_tema'),
    path('registrar_practica/', views.RegistrarPractica, name='registrar_practica'),

    # Sección reportes
    path('inicio/create/', views.create_unidad, name='create_unidad'),
    path('reporte/', views.visualizar_reporte, name='visualizar_reporte'),
    path('aula/', views.visualizar_contenido, name='aula_documento'),
    path('imprimir_unidad/<int:unidad_id>/', views.generar_unidad_pdf, name='imprimir_unidad'),


    path('recomendacion/', views.buscar_youtube, name='recomendacion'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler500 = 'tasks.views.server_error'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Create your models here.
class Unidad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Contenido(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion= models.TextField(blank=True)
    unidad = models.ForeignKey(Unidad, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Tema(models.Model):
    nombre = models.CharField(max_length=100)
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

def validate_pdf_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError("El archivo debe ser un PDF.")

def validate_pdf_size(value):
    if value.size > 10 * 1024 * 1024:  # Límite de tamaño: 10 MB
        raise ValidationError("El tamaño máximo del archivo es 10 MB.")

class Material(models.Model):
    enlace = models.URLField()
    archivo_pdf = models.FileField(upload_to='pdfs/', validators=[validate_pdf_extension, validate_pdf_size],
                                   default='default.pdf')
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)  # Relación de uno a muchos con Tema

    def __str__(self):
        return self.tema.nombre

class Ejercicio(models.Model):
    enunciado = models.TextField()
    opciones = models.JSONField()  # Almacena las opciones de respuesta como un JSON
    respuesta_correcta = models.IntegerField()  # Respuesta correcta en el campo 'opciones'
    material = models.ForeignKey(Material, on_delete=models.CASCADE, default=1)  # Relación con Material
    def __str__(self):
        return f"{self.enunciado}"

class Puntuacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE,default=9)
    fecha = models.DateTimeField(auto_now_add=True)
    puntaje = models.CharField(max_length=10, default='0/0')
    preguntas_respondidas = models.CharField(max_length=10, default='0/0')
    def __str__(self):
        return f"{self.usuario}"

    

tasks/forms.py
from django.forms import ModelForm
from .models import Unidad,Contenido,Tema,Material

class UnidadForm(ModelForm):
    class Meta:
        model = Unidad
        fields = ['nombre']

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.db import IntegrityError
from .models import Unidad, Contenido, Material, Tema, Ejercicio, Puntuacion
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import requires_csrf_token
from io import BytesIO
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from django.core.files.base import ContentFile
from django.core.exceptions import PermissionDenied
import json
from django.conf import settings
from isodate import parse_duration
import requests
import random
import pandas as pd
import plotly.express as px
from django.db.models import Count

# Create your views here.


def home(request):
    return render(request, 'home.html')


def model(request):
    return render(request, 'model.html')


def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                # Register User
                user = User.objects.create_user(
                    username=request.POST['username'], email=request.POST['email'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('perfil')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    'error': 'El usuario ya existe'
                })
        return render(request, 'signup.html', {
            'form': UserCreationForm,
            'error': 'Contraseña no coinciden'
        })


def signin(request):
    error = None
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return redirect('perfil')
            else:
                error = 'Usuario o Contraseña es incorrecto'
        else:
            error = 'Por favor, ingrese un nombre de usuario y contraseña válidos'
    else:
        form = AuthenticationForm()

    return render(request, 'signin.html', {
        'form': form,
        'error': error,
    })


@login_required
def change_password(request):
    if request.method == 'POST':
        new_password = request.POST['contraseña']
        user = request.user

        user.set_password(new_password)
        user.save()
        # Actualiza la sesión de autenticación
        update_session_auth_hash(request, user)

        return JsonResponse({'result': '1', 'message': 'Cambio de contraseña correctamente'})

    return JsonResponse({'result': '0', 'message': 'Error al modificar la contraseña, por favor intente nuevamente.'})


@login_required
def edit_usuario(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            username_id = request.POST.get('usuario_id')
            nuevo_username = request.POST.get('user')
            nombres = request.POST.get('nombres')
            apellidos = request.POST.get('apellidos')
            email = request.POST.get('email')
            try:
                usuario = get_object_or_404(User, username=username_id)
                # Verifica si el usuario que se quiere editar es el mismo que el usuario autenticado
                if usuario == request.user:
                    # Comprobamos si el nuevo username está disponible
                    if nuevo_username != usuario.username and User.objects.filter(username=nuevo_username).exists():
                        return JsonResponse({'result': '0', 'message': 'El nombre de usuario ya está en uso.'})

                    # Si el nuevo username es diferente, actualizamos el username
                    if email != usuario.username:
                        usuario.username = email
                    usuario.first_name = nombres
                    usuario.last_name = apellidos
                    usuario.email = nuevo_username
                    usuario.save()
                    return JsonResponse({'result': '1'})
                else:
                    raise PermissionDenied(
                        "No tienes permisos para editar este usuario.")
            except Exception as e:
                return JsonResponse({'result': '0', 'message': str(e)})
        else:
            raise PermissionDenied(
                "Debes estar autenticado para editar un usuario.")


@login_required
def get_user_data(request):
    if request.method == "GET" and "username" in request.GET:
        username = request.GET["username"]

        try:
            user = User.objects.get(username=username)
            user_data = {
                'username': user.username,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email
            }
            return JsonResponse(user_data)
        except User.DoesNotExist:
            return JsonResponse({'error': 'Usuario no encontrado.'}, status=404)
    else:
        return JsonResponse({'error': 'Petición inválida.'}, status=400)


@login_required
def profile(request):
    return render(request, 'profile.html')


@login_required
def signout(request):
    logout(request)
    return redirect('home')


@login_required
def inicio(request):
    puntuaciones_usuario = Puntuacion.objects.all()
    temas_practicados = {}
    for puntuacion in puntuaciones_usuario:
        tema_id = puntuacion.tema.id
        if tema_id in temas_practicados:
            temas_practicados[tema_id] += 1
        else:
            temas_practicados[tema_id] = 1
    temas_info = []
    for tema_id, practicas in temas_practicados.items():
        tema = Tema.objects.get(id=tema_id)
        tema_dict = {
            'id': tema_id,
            'tema': tema.nombre,
            'cantidad_estudiantes': practicas
        }
        temas_info.append(tema_dict)

    df = pd.DataFrame(temas_info)
    fig = px.bar(df, x='tema', y='cantidad_estudiantes', title='Prácticas por Tema',
                 color_discrete_sequence=['blue'], opacity=0.7)
    fig.update_layout(title_x=0.5)
    fig.update_traces(marker_line_width=0.1)
    fig.update_layout(yaxis_tickmode='linear', plot_bgcolor='white')
    fig.update_layout(
        xaxis_title="Tema",
        yaxis_title="Cantidad de Estudiantes",
        yaxis_tickmode='linear',
        plot_bgcolor='white',
        font=dict(family="Arial", size=12, color="black"),
        showlegend=False)
    grafico_html = fig.to_html(full_html=False)
    context = {
        'grafico_html': grafico_html
    }
    return render(request, 'inicio.html', context)

# Vista que renderiza la plantilla que lista los unidades registrados


@login_required
def vwUnidad(request):
    unidades_list = Unidad.objects.all()  # Obtener todos los registros de unidades

    # Configuración del paginador para mostrar 5 unidades por página
    paginator = Paginator(unidades_list, 5)

    page = request.GET.get('page')  # Obtener el número de página de la URL

    try:
        unidades = paginator.page(page)
    except PageNotAnInteger:
        # Si el número de página no es un número, mostrar la primera página
        unidades = paginator.page(1)
    except EmptyPage:
        # Si el número de página está fuera de rango, mostrar la última página
        unidades = paginator.page(paginator.num_pages)

    return render(request, 'create_unidad.html', {'unidad': unidades, 'btnUnidad': 'activado'})


@login_required
def create_unidad(request):
    if request.method == 'POST':
        nombre_unidad = request.POST.get('nombre')
        if not nombre_unidad:
            return JsonResponse({'result': '0', 'message': 'Por favor ingrese un nombre para la unidad.'})
        try:
            unUnidad = Unidad()
            unUnidad.nombre = request.POST['nombre']
            unUnidad.save()
            return JsonResponse({'result': '1'})
        except Exception as e:
            return JsonResponse({'result': '0', 'message': 'Error al modificar la unidad, por favor intente nuevamente.'})

# Vista que modifica los datos de un administrador


@login_required
def edit_unidad(request):
    if request.method == 'POST':
        nombre_unidad = request.POST.get('txtEdUnidadNombre')
        if not nombre_unidad:
            return JsonResponse({'result': '0', 'message': 'Por favor ingrese un nombre para la unidad.'})
        try:
            unUnidad = Unidad.objects.get(pk=request.POST['txtIdUnidad'])
            unUnidad.nombre = request.POST['txtEdUnidadNombre']
            unUnidad.save()
            messages.success(
                request, 'El administrador se modificó exitosamente.')
            return JsonResponse({'result': '1'})
        except Exception as e:
            return JsonResponse({'result': '0', 'message': 'Error al modificar la unidad, por favor intente nuevamente.'})

# Vista que busca a los administradores de forma filtrada


@login_required
def vwBuscarUnidad(request):
    if request.method == 'POST':
        try:
            buscarUnidad = request.POST['txtBuscarunidad']

tasks/templates/avance_alumno.html
{% extends 'profile.html' %}
{% block title %}Mi Avance{% endblock %}
{% load static %}
{% block content %}
<span class="fw-bold fs-4" style="color: #fdb128">MI AVANCE</span>
<div class="d-flex">
    <div class="p-2 flex-fill" style="max-width: 200px">
        <select id="unidad-select" class="form-select" aria-label="Unidad select" onchange="cargarContenidos()">
            <option value="">Selecciona una unidad</option>
            {% for unidad in unidades %}
            <option value="{{ unidad.id }}">{{ unidad.nombre }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="p-2 flex-fill" style="max-width: 300px">
        <select id="contenido-select" class="form-select" aria-label="Contenido select" onchange="cargarTemas()">
            <option selected>Selecciona un contenido</option>
        </select>
    </div>

    <div class="p-2 flex-fill" style="max-width: 300px">
        <select id="tema-select" class="form-select" aria-label="Tema select">
            <option selected>Selecciona un tema</option>
        </select>
    </div>
    <div class="p-2 flex-fill" style="max-width: 200px">
        <button id="filtrar" type="button" class="btn btn-primary" onclick="filtrarPuntuacion()" disabled>Buscar</button>
    </div>
    <!-- Botón de restablecimiento -->
    <div class="p-2 flex-fill" style="max-width: 200px">
        <button id="restablecer" class="btn btn-secondary">Restablecer</button>
        <script>
            document.getElementById('restablecer').addEventListener('click', function () {
              window.location.reload();
            });
          </script>
    </div>
    
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Tema</th>
            <th>Resultado corecto</th>
            <th>Puntaje</th>
            <th style="text-align: center;">Fecha</th>
        </tr>
    </thead>
    <tbody>
        {% if puntuaciones %}{% for puntuacion in puntuaciones %}
        <tr>
            <td>{{ puntuacion.tema }}</td>
            <td style="text-align: center;">{{ puntuacion.preguntas_respondidas }}</td>
            <td style="text-align: center;">{{ puntuacion.puntaje }}</td>
            <td>{{ puntuacion.fecha }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <p>¡Aún no hay progreso! Cuando veamos alguna actividad, los progresos se mostrarán aquí.</p>
        {% endif %}
        <p id="mensaje-vacio" style="display: none;">¡Aún no hay progreso con el tema seleccionado! Cuando veamos alguna actividad, los progresos se mostrarán aquí.</p>
    </tbody>
</table>
{% block javascript %}
<script src="{% static 'js/avance.js'%}"></script>
{% endblock %}

{% endblock %}

tasks/templates/contenido_alumno.html
{% extends 'profile.html' %}
{% load static %}
{% block title %}Contenido{% endblock %}
{% block content %}
<span class="fw-bold fs-4" style="color: #fdb128">CONTENIDO</span>
<div class="d-flex justify-content-between align-items-center gap-5 flex-wrap mt-3">
  {% if contenidos %} {% for contenido in contenidos %}
  <div class="card" style="width: 300px">
    <div class="card-body">
      <h5 class="card-title fw-bold">{{ contenido.nombre }}</h5>
      <p class="card-text" style="text-align: justify">
        {{ contenido.descripcion }}
      </p>
      <form action="{% url 'temas_alu' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ contenido.id }}">
        <button type="submit" 
                class="btn btn-sm w-100 rounded-4"
                style="background-color: #fdb128">
          <span class="text-white fw-bold">Ver más</span>
        </button>
      </form>
    </div>
  </div>
  {% endfor %} 
  {% else %}
  <div class="ilustracion d-flex justify-content-center align-items-center mt-5">
    <img style="width: 200px; height: 200px;" 
         src="{% static '../static/img/not-data.svg' %}">
  </div>
  <p class="text-center mt-3 fw-bold fs-6"
    style="color: #fdb128">
      No se encontraron resultados.
  </p>
  {% endif %}

</div>
{% endblock %}

tasks/templates/inicio.html
{% extends 'profile.html' %}
{% block title %}Inicio{% endblock %}
{% block content %}
<di class="container by-5">
    {% csrf_token %}
    <h4>Bienvenid@ a Smart Genius {% if user_email %}{{ user_email }}{% else %}Invitado{% endif %}</h4>

    {% if user.is_authenticated %}
    {% if perms.tasks.add_unidad %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                {{ grafico_html | safe }}
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}

    <!-- Barra de progreso circular -->
    <div class="circle-progress">
        {% if user.is_authenticated %}
        {% if perms.tasks.add_unidad %}
        <div class="circle-container">
            <div class="circle">
                <i class="fas fa-clipboard-check circle-icon"></i>
            </div>
            <div class="circle-label">Unidades</div>
        </div>
        <div class="circle-container">
            <div class="circle">
                <i class="fas fa-book-open circle-icon"></i>
            </div>
            <div class="circle-label">Contenidos</div>
        </div>
        <div class="circle-container">
            <div class="circle">
                <i class="fas fa-file-alt circle-icon"></i>
            </div>
            <div class="circle-label">Materiales</div>
        </div>
        <div class="circle-container">
            <div class="circle">
                <i class="fas fa-lightbulb circle-icon"></i>
            </div>
            <div class="circle-label">Temas</div>
        </div>
        {% else %}
        <div class="circle-container">
            <div class="circle">
                <i class="fa-solid fa-book-open circle-icon"></i>
            </div>
            <div class="circle-label">Contenido</div>
        </div>
        <div class="circle-container">
            <div class="circle">
                <i class="fa-solid fa-user circle-icon"></i>
            </div>
            <div class="circle-label">Perfil</div>
        </div>
        <div class="circle-container">
            <div class="circle">
                <i class="fa-solid fa-layer-group circle-icon"></i>
            </div>
            <div class="circle-label">Mi Avance</div>
        </div>
        {% endif %}
        {% endif %}
    </div>
    

</div>
{% endblock %}

tasks/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="icon" href="{% static '../static/img/Logo-Page.png' %}" type="image/png"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style-profile.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    {% block css %}
    {% endblock css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/4.0.2/autosize.min.js"></script>
</head>

<body>

    <input type="checkbox" id="panel-izquierdo-boton">
    <div class="panel-izquierdo">
        {% csrf_token %}
        <div class="panel-izquierdo-encabezados">
            <h3>
                <span class="fa-solid fa-square-root-variable"></span>
                <span> <a href="{% url 'inicio' %}">Smart Genius</a></span>
            </h3>
            <label for="panel-izquierdo-boton" class="fa-solid fa-bars"></label>
        </div>
        <div class="panel-izquierdo-opciones">
            <ul>
                {% if user.is_authenticated %}
                {% if perms.tasks.add_unidad %}
                <li>
                    <a class="btn-opcion {{ btnUnidad }}" href="{% url 'unidad' %}">
                        <span class="fas fa-clipboard-check"></span>
                        <span>Unidad</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'contenido' %}">
                        <span class="fas fa-book-open"></span>
                        <span>Contenido</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'temas' %}">

                        <span class="fas fa-lightbulb"></span>
                        <span>Temas</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'material' %}">
                        <span class="fas fa-file-alt"></span>
                        <span>Material</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'visualizar_reporte' %}">
                        <span class="fa-solid fa-clipboard-user"></span>
                        <span>Reportes Estudiantes</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'aula_documento' %}">
                        <span class="fa-solid fa-file"></span>
                        <span>Reportes Contenido</span>
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'contenido_alu' %}">
                        <span class="fa-solid fa-book-open"></span>
                        <span>Contenido</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'perfil_alu' %}">
                        <span class="fa-solid fa-user"></span>
                        <span>Perfil</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'avance_alu' %}">
                        <span class="fa-solid fa-layer-group"></span>
                        <span>Mi Avance</span>
                    </a>
                </li>
                <!--<li>
                    <a href="{% url 'recomendacion' %}">
                        <span class="fa-solid fa-layer-group"></span>
                        <span>Recomendacion</span>
                    </a>
                </li>-->
                {% endif %}
                <li>
                    <a href="{% url 'logout' %}">
                        <span class="fa-solid fa-right-from-bracket"></span>
                        <span>Cerrar Sesión</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="main-content">

        <header class="encabezados-contenido">
            <div class="search-wrapper">

            </div>

            <div class="social-icons me-4">
                <span class="fa-solid fa-user"></span>
                <span>{% if user_email %}{{ user_email }}{% else %}Invitado{% endif %}</span>
            </div>
        </header>

        <main>

            {% block content %}
            {% endblock %}


        </main>

    </div>

    <script>
        $(document).ready(function () {
            // Verificar si hay elementos en la selección
            var headerContent = $('.main-content .encabezados-contenido').children().length;
            var mainContent = $('.main-content main').children().length;

            if (headerContent === 0 || mainContent === 0) {
                // Redirigir a la página de inicio
                window.location.href = '/inicio/';
            }
            $("li").click(function () {
                var link = $(this).find("a").attr("href");
                if (link) {
                    window.location.href = link;
                }
            });
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/global.js'%}"></script>
    {% block js %}
    {% endblock js %}

</body>

</html>